- name: install prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: add docker key
  ansible.builtin.shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg 
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: set permission for docker gpg key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: "0644"

- name: add docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable"
    state: present
    filename: docker

- name: install docker CE and plugins
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: enable and start docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: addn users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ dockerUsers }}"